# Generated by Django 6.1.1 on 2026-09-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('carga_horaria', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='certificados/')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='certificados/')),
            ],
        ),
    ]
