# Generated by Django 6.1.1 on 2026-09-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chavierwebmidia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='certificado',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='certificados/'),
        ),
    ]
