# Generated by Django 6.1.1 on 2026-10-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chavierwebmidia', '0002_alter_certificado_certificado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtendimentoChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=150)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('servico', models.CharField(blank=True, max_length=150)),
                ('mensagens', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
